apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: harness-delegate-ng
spec:
  selector:
    app: hello-world   # ← THIS MUST MATCH YOUR DEPLOYMENT
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30036
      protocol: TCP
  type: ClusterIP
